### ISSUE TITLE
sony xperia m2 d2303 bootloop

### ISSUE THREAD

**Issue by zelinschi** [sonyxperiadev/device-sony-eagle#10]
I have a sony xperia m2 2303 wit android 4.4.2 update. Suddenly the device goes into bootloop without any action on software. I tried to repair with pc Companion first time ad with Emma second time. The third time i downloaded Flashtool and tried to flash the ftf file. I tried to flash all version of android (18.0.c.1.13/ 18.3.1.c.0.21/ 18.3.c.0.37 18.3.c.0.21. 18.3.c.0.40) but the phone wont't start up. With 18.3.c.1.13 is going in blue screen bootloop, and the others is going in a black screen (after sony logo) turning of an on. Please help me. I followed ol the tutorials and i tri to find only official roms. I tried to flash with bootloader locked and unlocked. Phone is still dead. Thank you... (alin jerpelea / sunt din romania).

**Comment by jerpelea** [comment]
Please flash 18.3.1.C.1.15, flash bootloader update and after this AOSP
(please use English)
