### ISSUE TITLE
Why you do not support device d2305?

### ISSUE THREAD

**Issue by nguyentuandat** [sonyxperiadev/device-sony-eagle#13]

**Comment by jerpelea** [comment]
We support only LTE devices on Open Devices but community can easy fork and add variants 
d2303 and d2305 devices are similar and support can be easy be added by a community developer.

**Comment by nguyentuandat** [comment]
thanks for answer :)

**Comment by tranphuong** [comment]
D2305 why not be running AOSP cyangenmod or so. D2303 is such runs . LTE only severance stars

**Comment by jerpelea** [comment]
D2305 can be easy added by a developper as a fork of d2303. We provide a reference for LTE only devices.

**Comment by tranphuong** [comment]
When such new official d2305 .
Apparently sonymobile launched new bootloader to flash the firmware and Ubuntu and Firefox os right .

**Comment by tranphuong** [comment]
So I have unlocked bootloader D2305 is no way to install Ubuntu or Firefox not so sir.

**Comment by jerpelea** [comment]
Open Devices program provides just a AOSP base. This base can be used by comunity developers to inovate. You should ask a comunity developer to support your device in that specific project.

**Comment by tranphuong** [comment]
So I try to install the D2303 to D2305 for machinery not corrupted

**Comment by tranphuong** [comment]
Tôi muốn có rom AOSP cho D2305. Khi nào có thì email cho tôi nha

**Comment by jerpelea** [comment]
There are differences between d2305 and d2303. Please ask project developper to add support for your device
