### ISSUE TITLE
aosp lollipop for xperia 2012

### ISSUE THREAD

**Issue by xehed** [sonyxperiadev/device-sony-eagle#2]
sir, what about older device? what about low end device? can we get lollipop too?
 why it's always flagship, why it's always high end device?
my Tipo had never get an update since I buy it? please... can we get it too, at least for the first & last update?? :'(

**Comment by jerpelea** [comment]
Sony AOSP project is intended to provide a stable base for custom ROMs with no hacks 
for older devices this is not possible
