### ISSUE TITLE
Sensors are missing libyasalgo.so

### ISSUE THREAD

**Issue by AdFad666** [sonyxperiadev/device-sony-eagle#3]
included sensors lib depends on missing libyasalgo.so:

D/SensorService(665): nuSensorService starting...
E/HAL(665): load: module=/system/lib/hw/sensors.msm8226.so
E/HAL(665): dlopen failed: could not load library "libyasalgo.so" needed by "sensors.msm8226.so"; caused by library "libyasalgo.so" not found
E/SensorService(665): couldn't load sensors module (Invalid argument)

**Comment by jerpelea** [comment]
problem fixed in package 6
