### ISSUE TITLE
Getting this error while building. Please help me fix this.

### ISSUE THREAD

**Issue by SkyWalker653** [sonyxperiadev/device-sony-eagle#6]
make: stat: vendor/sony/yukon/proprietary/lib/hw/copybit.msm8226.so: Permission denied
make: *** No rule to make target 'vendor/sony/yukon/proprietary/lib/hw/copybit.msm8226.so', needed by 'out/target/product/eagle/obj/lib/copybit.msm8226.so'.  Stop.
make: *** Waiting for unfinished jobs....
target thumb C++: libaudiopolicy_legacy <= hardware/libhardware_legacy/audio/audio_policy_hal.cpp

**Comment by jerpelea** [comment]
after you unzipped vendor file 
you have to change perssions 
sudo chown -R user.group vendor
where user.group are your local user and group

**Comment by jerpelea** [comment]
package v7 has fixed this issue
