### ISSUE TITLE
device not booting after flashing

### ISSUE THREAD

**Issue by stoyanj** [sonyxperiadev/device-sony-eagle#8]
Hello,

I did follow 

http://developer.sonymobile.com/knowledge-base/open-source/open-devices/aosp-build-instructions/how-to-build-aosp-lollipop-for-unlocked-xperia-devices/

all the instructions, step by step.

Everythign builds OK, but once I flash the device it is just not booting.

Nothing happens!

I did a sync today but still not able.

Thanks alot!

**Comment by jerpelea** [comment]
Please specify your device and latest official release you flashed

**Comment by stoyanj** [comment]
Hello,

D2303.

Thank you very much for your response !

**Comment by jerpelea** [comment]
You neef to flash first Sony 18.3 software and then AOSP

**Comment by stoyanj** [comment]
Hello,

I am sorry I am gettign confused (sorry again if question is wrong and stupid).

I unlocked device bootloader follwoing the instructions, so I am not sure what software I have to flash first?

Please note absolutly the same problem I have with bildin 4.4

Do you mean I need to change bootloader?

Thanks again!

**Comment by stoyanj** [comment]
Hello,

I have just checked the device is running firmware Build 18.3.1.C.0.21, so if there anything I need to update?

Thank you very much for your time

**Comment by stoyanj** [comment]
Hello,

I also checked the ../out/target/product/eagle

all folders (not img files but folders) seems pretty OK but device not booting.

Is there anyway for me to gether some info durign boot why it is not loading?

Thank you very much!

**Comment by jerpelea** [comment]
if device is flashed with 18.3 software will fail to boot aosp images please flash with the software i have specified

**Comment by jerpelea** [comment]
if device is flashed with 18.3.x.x.x software will fail to boot aosp images 
please flash it with 18.0.x.x.x software

**Comment by stoyanj** [comment]
Hello,

Thank you very much for your help!
All works as you described. 
I got it all working now (well as much as Sony AOSP is working, i.e. no camera for example).

Thanks again!
